# Generated by Django 5.0.1 on 2024-01-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskphoto',
            name='photo',
            field=models.ImageField(upload_to='task_image/'),
        ),
    ]
